name: Hello World
on: workflow_dispatch    
jobs:
    Hello:
        runs-on: ubuntu-latest
        steps:
            - name: hello steps
            run: 
            echo "this is the first line"
            echo "this is the second line"
            echo "this is the third line"
