name: Hello World

on: workflow_dispatch

jobs:
  
  build:
   
    runs-on: ubuntu-latest

    
    steps:
    
      - name: Hello step
        run: echo "This is the test"
      
      - name: Run a multi-line script
        run: |
          echo "Welcome to GHA",
          echo "Another set"
