name: Hello World
on: workflow_dispatch    
jobs:
    Hello:
        runs-on: ubuntu-latest
    steps:
      - name: Hello steps:      
        run: |
          echo "Welcome to GHA",
          echo "Another set"
          echo "This is the third line" 
